import Head from "next/head";
import { useState } from "react";
import TabHead from "../components/TabHead";
import InfoCard from "../components/InfoCard";

export default function Home({ user }) {
  const [showData, setShowData] = useState(null);

  return (
    <div className="bg-neutral-700 text-white min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-8">
        <TabHead user={user} setShowData={setShowData} />
        <div className="pt-20 pb-6">
          {showData?.map((ride, key) => (
            <InfoCard ride={ride} key={key} />
          ))}
        </div>
      </div>
    </div>
  );
}
